### ISSUE TITLE
Connection refused on Ubuntu 24.04 with docker

### ISSUE THREAD

**Issue by marekzima** [qiuhaotc/WebSSH#8]
Installation was successful but the app is not answering on specified port 80 even from server on which docker runs.
---
netcat -vzn 172.17.0.2 80
(UNKNOWN) [172.17.0.2] 80 (http) : Connection refused
--
ping 172.17.0.2
PING 172.17.0.2 (172.17.0.2) 56(84) bytes of data.
64 bytes from 172.17.0.2: icmp_seq=1 ttl=64 time=0.094 ms
64 bytes from 172.17.0.2: icmp_seq=2 ttl=64 time=0.039 ms

So. I'm able to reach docker container, but web service is unreachable :(

**Comment by qiuhaotc** [comment]
Not sure, maybe change the bind port to 8080 then try?

`docker run -d --name webssh -p 8080:80 -e ShellConfiguration__Users__0__Password="your_password" --restart=always qiuhaotc/webssh
`

**Comment by marekzima** [comment]
Does not work eather :(Marek---Ing. Marek Zimae-mail: ***@***.***: http://www.marekzima.comDňa 19. 7. 2024 o 15:54 užívateľ Nuclear Weapon ***@***.***> napísal:﻿
Not sure, maybe change the bind port to 8080 then try?
docker run -d --name webssh -p 8080:80 -e ShellConfiguration__Users__0__Password="your_password" --restart=always qiuhaotc/webssh

**Comment by marekzima** [comment]
It looks like the web service (port 80) is not started or something like that, because there is nothing listening on port 80.

**Comment by marekzima** [comment]
Your project is .NET8, can it be the problem that I'm running it on Linux (Ubuntu) OS and not Windows OS?

**Comment by qiuhaotc** [comment]
I see, by checking the logs in the container ```docker logs webssh```, I found that the default port is 8080 rather than 80
```log 
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:8080
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]

```

So, you need to change the port from 80 to 8080
